baseurl = "http://andreiformiga.com/"
#languageCode = "pt-BR"
title = "Andrei Formiga"

metaDataFormat = "toml"

home = "início"

theme = "hyde-y"

disqusShortname = "andreiformigacom"

pygmentsStyle = "monokai"
pygmentsUseClasses = "true"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[author]
  name = "Andrei Formiga"

[params]
  topline = "math is hard, let's go shopping!"

  sidebar = "left"

  highlight = "default"
  
  github = "tautologico"
  twitter = "andreiformiga"
  
  googleAnalytics = "UA-3998702-3"

